# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mackenzie K. Brooks
email: mackenziekbrooks@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Academic librarian. Interests: Digital Humanities, the promise of linked data, the myth of the digital native, questioning the book as object, feminism, and rejecting the cult of busy. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.mackenziekbrooks.info" # the base hostname & protocol for your site
twitter_username: mackymoo
github_username: mackenziekbrooks
goodreads_username: mackenziekbrooks

# Build settings
markdown: kramdown
